### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by ekuiter** [SoftVarE-Group/Course-on-Software-Product-Lines#10]
I have updated most of the README file. Do we want to list contributors to the exercise sheets as well (e.g., Chico and Sandra)?

**Comment by tthuem** [comment]
Maybe when the exercises are published?

We do also have minor contributions by Benno and Chico already in the slides, but still there is a quite large gap to main contributors.

**Comment by ekuiter** [comment]
Okay. Maybe we can then distinguish main + minor contributors. Or list the exercise contributors only in the exercise repository.

**Comment by tthuem** [comment]
Or even both. Separating both main and further contributors for lecture and exercise separately.

**Comment by ekuiter** [comment]
I updated the lists of major and minor contributors in both the main and exercise repositories (based on all information available to me through git logs).

**Comment by tthuem** [comment]
Thanks!
