### ISSUE TITLE
Compiler Errors for 14-conclusion.tex

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/Course-on-Software-Product-Lines#15]
Currently, this file cannot be compiled. Shall we fix it or will we rather remove that lecture in future?

**Comment by ekuiter** [comment]
The file referenced a nonexisting slide in the testing lecture, which I have fixed now.

The file should now compile as usual with

```
docker run --rm -v $(pwd)/..:/spl -w /spl/slides texlive/texlive:TL2021-historic make handout=y
```

(all other slides have to be compiled first)

Whether we need this lecture at all is another question, now that we have lecture 12 with the course summary.

**Comment by tthuem** [comment]
Thanks! It does not hurt right now. Let's see.
