### ISSUE TITLE
Makefile Should Reset Changed Lines to Defaults for Commits

### ISSUE THREAD

**Issue by tthuem** [SoftVarE-Group/Course-on-Software-Product-Lines#3]
Right now, the makefile changes the source files (*.tex) to set handout and university. Unfortunately, it is hard to track other changes in the tex files due to these changes and they can easily be committed to the repository.

Can we reset the files to their default values (handout and no university) once make is done? Does this negatively impact incremental compilation of the files?

**Comment by ekuiter** [comment]
I suppose we could maybe pass these as "environment variables" to Latex (not sure if that's possible) or only write them into a single file, which is then included (and not committed into the repository).

**Comment by ekuiter** [comment]
I changed the Makefile to not modify source files anymore as suggested above. Default values are stored in `slides/template/options.tex`.

**Comment by tthuem** [comment]
Works great, thanks!
