### ISSUE TITLE
[Bug] Missing `-paper` files

### ISSUE THREAD

**Issue by pmbittner** [SoftVarE-Group/Course-on-Software-Product-Lines#30]
Some standalone graphics in `pics` cannot be compiled because they are missing a respective `*-paper` file. Affected graphics are
- `pics/evonance/fmrefactoring.tex` missing `fmrefactoring-paper`
- `pics/evonance/splevolution.tex` missing `splevolution-paper`
- `pics/interactions/variabilitybugdatabase.tex` missing `variabilitybugdatabase-paper`
- `pics/interactions/variabilitybugdatabase-patterns.tex` missing `variabilitybugdatabase-paper`

**Comment by tthuem** [comment]
This is designed as is. We have no right to publish the papers here, but it is easy to download and rename the PDF, if needed.
