### ISSUE TITLE
Depending on the Latex version, inappropriate margins are inserted at the top of boxes

### ISSUE THREAD

**Issue by ekuiter** [SoftVarE-Group/Course-on-Software-Product-Lines#8]
On the latest TexLive version, the following happens:
![grafik](https://user-images.githubusercontent.com/4258713/233370767-9fcc7a54-d077-4927-aa62-bc9195a3a476.png)
At the top of each non-itemize/enumerate box, there is a large margin. It should instead look like this (no margin above "a software product line"):
![grafik](https://user-images.githubusercontent.com/4258713/233371091-b80c8ee7-a8af-432e-9ee5-9a9d225e9113.png)

This is reproducible with `docker run --rm -v $(pwd)/..:/spl -w /spl/slides texlive/texlive make`.

I believe this happened when we updated the SlideTemplate to another branch (release) a few weeks ago, so the issue is probably within the SlideTemplate or its interaction with our lecture.

Currently, the consequence is that only @tthuem can compile lectures.

**Comment by Benno2000** [comment]
If this bug is caused by the TeXLive version, I am not sure whether and how this can be fixed in the template itself.

**Comment by Benno2000** [comment]
I just tested the behaviour with my TeX Live 2022 Installation which worked normally. The I upgraded my TeX Live Version to 2023 and got the same issue.

However, it seems to be a problem with the template as the bug doesn't exist in an empty document with only a tcolorbox:
```
\documentclass{beamer}

\usepackage{tcolorbox}

\begin{document}
    \begin{frame}
        \begin{tcolorbox}
            Test
        \end{tcolorbox}
    \end{frame}
\end{document}
```

However, as I don't understand the concrete implementation of the colorboxes in the template, It's hard for me to debug the issue. Maybe Florian Sihler, who implemented the colorboxes in the template, can help us with this problem. It seems to be a general problem with `tcolorbox`es in TeX Live 2023.

**Comment by ekuiter** [comment]
Thanks for checking @Benno2000 ! @EagleoutIce, do you have an idea what might be happening here?

**Comment by tthuem** [comment]
Please document this issue in the Template repository and continue the discussion over there. A link here should be sufficient.

**Comment by Benno2000** [comment]
I created an issue for this in the template repo: https://github.com/SoftVarE-Group/SlideTemplate/issues/58

**Comment by tthuem** [comment]
@ekuiter Could you check whether the problem still occurs? It was never a problem on my machine, so hard to check for me.

**Comment by ekuiter** [comment]
The issue seems to be fixed. Compiling with the historic version of texlive no longer seems to produce a difference to the most recent version of texlive on Arch Linux.
