### ISSUE TITLE
Footer on second slide

### ISSUE THREAD

**Issue by ekuiter** [SoftVarE-Group/Course-on-Software-Product-Lines#9]
On the second slide of each lecture, there is a trailing `1.` which is somewhat unpleasant to look at:

![grafik](https://user-images.githubusercontent.com/4258713/233375069-454c4a99-f11d-424e-ae97-ea53b30136d8.png)

**Comment by tthuem** [comment]
Benno, as we automatically set the subtitle now, it seems that it is not empty anymore and shown. Any ideas how to avoid that without changes in the template?

**Comment by Benno2000** [comment]
How does the subtitle get set automatically?

**Comment by tthuem** [comment]
https://github.com/SoftVarE-Group/Course-on-Software-Product-Lines/blob/main/slides/template/slidetemplate.tex

```
\AtBeginLecture{
	\part{}
	\subtitle{\insertlecturenumber. \insertlecture}
```

However, it does not seem to be the subtitle but rather the section which causes the problem.

**Comment by tthuem** [comment]
Apparently, this is fixed in the most recent version. Not sure whether there was a fix in the template or the SPL slides though.
